version: "3.8"
services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong

  kong:
    image: kong/kong-gateway:latest
    depends_on:
      - kong-database
      - redis
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PLUGINS: bundled,rate-limiting
    ports:
      - "8000:8000"
      - "8001:8001"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

